version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: yak
    main: ./cmd/yak
    binary: yak
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.Commit}}'
      - -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: yak-cli
    name_template: "yak-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"

dockers:
  - image_templates:
      - "ghcr.io/santi1s/yak:{{ .Version }}-amd64"
      - "ghcr.io/santi1s/yak:latest-amd64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--builder=multiarch"
    ids:
      - yak
  - image_templates:
      - "ghcr.io/santi1s/yak:{{ .Version }}-arm64"
      - "ghcr.io/santi1s/yak:latest-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--builder=multiarch"
    ids:
      - yak

docker_manifests:
  - name_template: "ghcr.io/santi1s/yak:{{ .Version }}"
    image_templates:
      - "ghcr.io/santi1s/yak:{{ .Version }}-amd64"
      - "ghcr.io/santi1s/yak:{{ .Version }}-arm64"
  - name_template: "ghcr.io/santi1s/yak:latest"
    image_templates:
      - "ghcr.io/santi1s/yak:latest-amd64"
      - "ghcr.io/santi1s/yak:latest-arm64"