// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortRollout(arg1, arg2) {
  return window['go']['main']['App']['AbortRollout'](arg1, arg2);
}

export function CreateJWTClient(arg1) {
  return window['go']['main']['App']['CreateJWTClient'](arg1);
}

export function CreateJWTServer(arg1) {
  return window['go']['main']['App']['CreateJWTServer'](arg1);
}

export function CreateSecret(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateSecret'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSecret'](arg1, arg2, arg3);
}

export function GetArgoApps(arg1) {
  return window['go']['main']['App']['GetArgoApps'](arg1);
}

export function GetArgoCDServerFromProfile() {
  return window['go']['main']['App']['GetArgoCDServerFromProfile']();
}

export function GetCurrentAWSProfile() {
  return window['go']['main']['App']['GetCurrentAWSProfile']();
}

export function GetRolloutStatus(arg1, arg2) {
  return window['go']['main']['App']['GetRolloutStatus'](arg1, arg2);
}

export function GetRollouts(arg1) {
  return window['go']['main']['App']['GetRollouts'](arg1);
}

export function GetSecretData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSecretData'](arg1, arg2, arg3);
}

export function GetSecrets(arg1, arg2) {
  return window['go']['main']['App']['GetSecrets'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoginToArgoCD(arg1) {
  return window['go']['main']['App']['LoginToArgoCD'](arg1);
}

export function PauseRollout(arg1, arg2) {
  return window['go']['main']['App']['PauseRollout'](arg1, arg2);
}

export function PromoteRollout(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteRollout'](arg1, arg2, arg3);
}

export function RefreshArgoApp(arg1, arg2) {
  return window['go']['main']['App']['RefreshArgoApp'](arg1, arg2);
}

export function RestartRollout(arg1, arg2) {
  return window['go']['main']['App']['RestartRollout'](arg1, arg2);
}

export function SetRolloutImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRolloutImage'](arg1, arg2, arg3, arg4);
}

export function SuspendArgoApp(arg1, arg2) {
  return window['go']['main']['App']['SuspendArgoApp'](arg1, arg2);
}

export function SyncArgoApp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncArgoApp'](arg1, arg2, arg3, arg4);
}

export function TestSimpleApps() {
  return window['go']['main']['App']['TestSimpleApps']();
}

export function TestSimpleArray() {
  return window['go']['main']['App']['TestSimpleArray']();
}

export function UnsuspendArgoApp(arg1, arg2) {
  return window['go']['main']['App']['UnsuspendArgoApp'](arg1, arg2);
}

export function UpdateSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSecret'](arg1, arg2, arg3);
}
