clusters:
  production:
    endpoint: https://vault-prod.doctolib.tech:8200
  shared:
    endpoint: https://vault-shared.doctolib.tech:8200

platforms:
  cicd-staging:
    clusters:
      - shared
    awsProfile: cicd-staging-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      eu-west-1: cicd-staging-aws-eu-west-1
  common:
    clusters:
      - shared
      - production
    awsProfile: shared-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      terraform: terraform
  corp-it-production:
    clusters:
      - shared
    awsProfile: corp-it-production-sso
    awsRegion: eu-central-1
    vaultRole: sre
  corp-it-staging:
    clusters:
      - shared
    awsProfile: corp-it-staging-sso
    awsRegion: eu-central-1
    vaultRole: sre
  data-prod:
    clusters:
      - shared
    awsProfile: data-production-sso
    awsRegion: eu-central-1
    vaultRole: sre
  data-staging:
    clusters:
      - shared
    awsProfile: data-staging-sso
    awsRegion: eu-central-1
    vaultRole: sre
  dev:
    clusters:
      - shared
    awsProfile: dev-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      de: dev-aws-de-fra-1
      fr: dev-aws-fr-par-1
      global: dev-aws-global
  interf:
    clusters:
      - shared
    awsProfile: interf-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      terraform: terraform
      de: interf
      global: interf-aws-global
  logging:
    clusters:
      - shared
    awsProfile: logging-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      de: logging-aws-de-fra-1
  production:
    clusters:
      - production
    awsProfile: prd-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      terraform: terraform
      de: prd-aws-de-fra-1
      fr: prd-aws-fr-par-1
      global: prd-aws-global
  preprod:
    clusters:
      - shared
    awsProfile: preprod-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      terraform: terraform
      de: preprod
      fr: preprod-aws-fr-par-1
      global: preprod-aws-global
  security:
    clusters:
      - shared
    awsProfile: security-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      de: security-aws-de-fra-1
      global: security-aws-global
  shared:
    clusters:
      - production
    awsProfile: shared-sso
    awsRegion: eu-central-1
    vaultRole: sre
  siilo:
    clusters:
      - shared
    awsProfile: siilo-sso
    awsRegion: eu-central-1
    vaultRole: sre
  staging:
    clusters:
      - shared
    awsProfile: staging-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      terraform: terraform
      de: staging
      fr: staging-aws-fr-par-1
      global: staging-aws-global
  testing:
    clusters:
      - shared
    awsProfile: testing-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      de: testing
  transit:
    clusters:
      - production
    awsProfile: transit-sso
    awsRegion: eu-central-1
    vaultRole: sre
  tooling:
    clusters:
      - shared
    awsProfile: tooling-sso
    awsRegion: eu-central-1
    vaultRole: sre
    environments:
      de: tooling
      global: tooling-aws-global
      eu-west-1: tooling-aws-eu-west-1
