// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortRollout(arg1, arg2) {
  return window['go']['main']['App']['AbortRollout'](arg1, arg2);
}

export function CreateJWTClient(arg1) {
  return window['go']['main']['App']['CreateJWTClient'](arg1);
}

export function CreateJWTServer(arg1) {
  return window['go']['main']['App']['CreateJWTServer'](arg1);
}

export function CreateSecret(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateSecret'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteEnvironmentProfile(arg1) {
  return window['go']['main']['App']['DeleteEnvironmentProfile'](arg1);
}

export function DeleteSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSecret'](arg1, arg2, arg3);
}

export function GetAWSProfiles() {
  return window['go']['main']['App']['GetAWSProfiles']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetArgoApps(arg1) {
  return window['go']['main']['App']['GetArgoApps'](arg1);
}

export function GetArgoCDServerFromProfile() {
  return window['go']['main']['App']['GetArgoCDServerFromProfile']();
}

export function GetCurrentAWSProfile() {
  return window['go']['main']['App']['GetCurrentAWSProfile']();
}

export function GetEnvironmentProfiles() {
  return window['go']['main']['App']['GetEnvironmentProfiles']();
}

export function GetEnvironmentVariables() {
  return window['go']['main']['App']['GetEnvironmentVariables']();
}

export function GetKubeconfig() {
  return window['go']['main']['App']['GetKubeconfig']();
}

export function GetRolloutStatus(arg1, arg2) {
  return window['go']['main']['App']['GetRolloutStatus'](arg1, arg2);
}

export function GetRollouts(arg1) {
  return window['go']['main']['App']['GetRollouts'](arg1);
}

export function GetSecretData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSecretData'](arg1, arg2, arg3);
}

export function GetSecrets(arg1, arg2) {
  return window['go']['main']['App']['GetSecrets'](arg1, arg2);
}

export function GetShellEnvironment() {
  return window['go']['main']['App']['GetShellEnvironment']();
}

export function GetShellPATH() {
  return window['go']['main']['App']['GetShellPATH']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportShellEnvironment() {
  return window['go']['main']['App']['ImportShellEnvironment']();
}

export function LoadEnvironmentProfile(arg1) {
  return window['go']['main']['App']['LoadEnvironmentProfile'](arg1);
}

export function LoginToArgoCD(arg1) {
  return window['go']['main']['App']['LoginToArgoCD'](arg1);
}

export function PauseRollout(arg1, arg2) {
  return window['go']['main']['App']['PauseRollout'](arg1, arg2);
}

export function PromoteRollout(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteRollout'](arg1, arg2, arg3);
}

export function RefreshArgoApp(arg1, arg2) {
  return window['go']['main']['App']['RefreshArgoApp'](arg1, arg2);
}

export function RestartRollout(arg1, arg2) {
  return window['go']['main']['App']['RestartRollout'](arg1, arg2);
}

export function SaveEnvironmentProfile(arg1) {
  return window['go']['main']['App']['SaveEnvironmentProfile'](arg1);
}

export function SetAWSProfile(arg1) {
  return window['go']['main']['App']['SetAWSProfile'](arg1);
}

export function SetKubeconfig(arg1) {
  return window['go']['main']['App']['SetKubeconfig'](arg1);
}

export function SetPATH(arg1) {
  return window['go']['main']['App']['SetPATH'](arg1);
}

export function SetRolloutImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRolloutImage'](arg1, arg2, arg3, arg4);
}

export function SetTfInfraRepositoryPath(arg1) {
  return window['go']['main']['App']['SetTfInfraRepositoryPath'](arg1);
}

export function SuspendArgoApp(arg1, arg2) {
  return window['go']['main']['App']['SuspendArgoApp'](arg1, arg2);
}

export function SyncArgoApp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncArgoApp'](arg1, arg2, arg3, arg4);
}

export function TestSimpleArray() {
  return window['go']['main']['App']['TestSimpleArray']();
}

export function UnsuspendArgoApp(arg1, arg2) {
  return window['go']['main']['App']['UnsuspendArgoApp'](arg1, arg2);
}

export function UpdateSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSecret'](arg1, arg2, arg3);
}
