name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-cli:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build yak CLI
        run: |
          # Build for multiple architectures
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o yak-darwin-amd64 ./cmd/yak
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o yak-darwin-arm64 ./cmd/yak
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o yak-linux-amd64 ./cmd/yak
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o yak-windows-amd64.exe ./cmd/yak

      - name: Create CLI Archives
        run: |
          tar -czf yak-darwin-amd64.tar.gz yak-darwin-amd64
          tar -czf yak-darwin-arm64.tar.gz yak-darwin-arm64
          tar -czf yak-linux-amd64.tar.gz yak-linux-amd64
          zip yak-windows-amd64.zip yak-windows-amd64.exe

      - name: Upload CLI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-binaries
          path: |
            yak-*.tar.gz
            yak-*.zip

  build-gui:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin/amd64,darwin/arm64
            name: darwin
          - os: ubuntu-latest
            platform: linux/amd64
            name: linux
          - os: windows-latest
            platform: windows/amd64
            name: windows
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install frontend dependencies
        run: |
          cd yak-gui/frontend
          npm ci

      - name: Build Wails GUI
        run: |
          cd yak-gui
          wails build --platform ${{ matrix.platform }}

      - name: Debug build output
        run: |
          echo "=== Build directory structure ==="
          find yak-gui -name "*.app" -o -name "yak-gui" -o -name "yak-gui.exe" 2>/dev/null || true
          echo "=== yak-gui/build contents ==="
          ls -la yak-gui/build/ 2>/dev/null || echo "build directory not found"
          echo "=== yak-gui/build/bin contents ==="
          ls -la yak-gui/build/bin/ 2>/dev/null || echo "bin directory not found"

      - name: Create GUI Archives (macOS)
        if: matrix.name == 'darwin'
        run: |
          cd yak-gui
          if [ -f "build/bin/yak-gui.app/Contents/MacOS/yak-gui" ]; then
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui.app
          elif [ -d "build/bin/yak-gui.app" ]; then
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui.app
          elif [ -f "build/bin/yak-gui" ]; then
            # Fallback if .app bundle wasn't created
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui
          else
            echo "No macOS binary found in expected locations"
            exit 1
          fi

      - name: Create GUI Archives (Linux)
        if: matrix.name == 'linux'
        run: |
          cd yak-gui
          if [ -f "build/bin/yak-gui" ]; then
            tar -czf ../yak-gui-linux-amd64.tar.gz -C build/bin yak-gui
          else
            echo "No Linux binary found at build/bin/yak-gui"
            exit 1
          fi

      - name: Create GUI Archives (Windows)
        if: matrix.name == 'windows'
        run: |
          cd yak-gui
          if (Test-Path "build/bin/yak-gui.exe") {
            Compress-Archive -Path "build/bin/yak-gui.exe" -DestinationPath "../yak-gui-windows-amd64.zip"
          } else {
            Write-Host "No Windows binary found at build/bin/yak-gui.exe"
            exit 1
          }

      - name: Upload GUI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.name }}
          path: yak-gui-*

  release:
    needs: [build-cli, build-gui]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CLI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-binaries

      - name: Download GUI Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: gui-*
          merge-multiple: true

      - name: Calculate Checksums
        run: |
          shasum -a 256 *.tar.gz *.zip > checksums.txt || true
          cat checksums.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yak-*.tar.gz
            yak-*.zip
            yak-gui-*.tar.gz
            yak-gui-*.zip
            checksums.txt
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}