name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure buildx for multi-arch
        run: docker buildx rm multiarch || true; docker buildx create --use --name multiarch

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-gui:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin/amd64,darwin/arm64
            name: darwin
          - os: ubuntu-latest
            platform: linux/amd64
            name: linux
          - os: windows-latest
            platform: windows/amd64
            name: windows
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Install frontend dependencies
        run: |
          cd yak-gui/frontend
          npm ci

      - name: Build Wails GUI
        run: |
          cd yak-gui
          wails build --platform ${{ matrix.platform }}

      - name: Debug build output
        run: |
          echo "=== Build directory structure ==="
          find yak-gui -name "*.app" -o -name "yak-gui" -o -name "yak-gui.exe" 2>/dev/null || true
          echo "=== yak-gui/build contents ==="
          ls -la yak-gui/build/ 2>/dev/null || echo "build directory not found"
          echo "=== yak-gui/build/bin contents ==="
          ls -la yak-gui/build/bin/ 2>/dev/null || echo "bin directory not found"

      - name: Create GUI Archives (macOS)
        if: matrix.name == 'darwin'
        run: |
          cd yak-gui
          # Wails creates separate arch-specific .app bundles, package them together
          if [ -d "build/bin/yak-gui-amd64.app" ] && [ -d "build/bin/yak-gui-arm64.app" ]; then
            # Create universal binary by combining both architectures
            mkdir -p build/bin/yak-gui.app/Contents/MacOS
            lipo -create \
              build/bin/yak-gui-amd64.app/Contents/MacOS/yak-gui \
              build/bin/yak-gui-arm64.app/Contents/MacOS/yak-gui \
              -output build/bin/yak-gui.app/Contents/MacOS/yak-gui
            # Copy other resources from one of the apps (they should be identical)
            cp -r build/bin/yak-gui-amd64.app/Contents/Info.plist build/bin/yak-gui.app/Contents/
            cp -r build/bin/yak-gui-amd64.app/Contents/Resources build/bin/yak-gui.app/Contents/ 2>/dev/null || true
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui.app
          elif [ -d "build/bin/yak-gui-amd64.app" ]; then
            # Only amd64 build available
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui-amd64.app
          elif [ -d "build/bin/yak-gui-arm64.app" ]; then
            # Only arm64 build available  
            tar -czf ../yak-gui-darwin-universal.tar.gz -C build/bin yak-gui-arm64.app
          else
            echo "No macOS .app bundles found"
            exit 1
          fi

      - name: Create GUI Archives (Linux)
        if: matrix.name == 'linux'
        run: |
          cd yak-gui
          if [ -f "build/bin/yak-gui" ]; then
            tar -czf ../yak-gui-linux-amd64.tar.gz -C build/bin yak-gui
          else
            echo "No Linux binary found at build/bin/yak-gui"
            exit 1
          fi

      - name: Create GUI Archives (Windows)
        if: matrix.name == 'windows'
        run: |
          cd yak-gui
          if (Test-Path "build/bin/yak-gui.exe") {
            Compress-Archive -Path "build/bin/yak-gui.exe" -DestinationPath "../yak-gui-windows-amd64.zip"
          } else {
            Write-Host "No Windows binary found at build/bin/yak-gui.exe"
            exit 1
          }

      - name: Upload GUI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.name }}
          path: yak-gui-*

  release-gui:
    needs: [goreleaser, build-gui]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download GUI Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: gui-*
          merge-multiple: true

      - name: Upload GUI binaries to existing release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yak-gui-*.tar.gz
            yak-gui-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}