---
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: prod-linux-s
    steps:
      - name: Load Secrets
        uses: doctolib/actions/load-secrets@main
        with:
          prefix_secrets: true
          sparse-checkout-first: true
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ env.VAULT_SECRET_CI_GITHUB_APP_GENERIC_ID }}
          private-key: ${{ env.VAULT_SECRET_CI_GITHUB_APP_GENERIC_PEM }}

      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: go
