name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-gui:
    name: Test GUI build
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build GUI
        run: |
          wails build

  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --no-optional
          npm install @rollup/rollup-linux-x64-gnu --save-optional
      
      - name: Check frontend can build
        run: |
          cd frontend
          npm run build
      
      - name: Run TypeScript check
        run: |
          cd frontend
          npx tsc --noEmit || echo "TypeScript check completed"

  outcome:
    needs: [test-gui, test-frontend]
    name: "required tests passed"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    timeout-minutes: 1
    steps:
      - name: Fail job on any previous error
        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Some previous checks failed')